version: '3.8'

services:
  mysql:
    image: mysql-container-export
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"                   # replace with your actual root password
      MYSQL_DATABASE: tihan_project_management  # optional
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    image: nidhi
    container_name: nidhi
    ports:
      - "8080:80"
    depends_on:
      - mysql
    #volumes:
    #  - ./www:/var/www/html             # optional: map your local code

volumes:
  mysql_data:
