version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
      MYSQL_DATABASE: tihan_project_management
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    image: nidhi
    container_name: nidhi
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:

